name: ⚡ Performance Issue
description: Report a performance problem or slowdown
title: "[Performance]: "
labels: ["performance", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a performance issue! Please provide details about the performance problem you're experiencing.

  - type: textarea
    id: description
    attributes:
      label: Performance Issue Description
      description: Describe the performance problem you're experiencing
      placeholder: |
        - The application is slow when...
        - Starting databases takes too long...
        - UI is laggy when...
    validations:
      required: true

  - type: dropdown
    id: affected-area
    attributes:
      label: Affected Area
      description: Which part of the application is affected?
      options:
        - Application Startup
        - Database Operations (Start/Stop)
        - UI Rendering
        - Port Checking
        - Process Management
        - File Watching
        - System Monitoring
        - Auto-Update
        - Other
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the performance issue
      placeholder: |
        1. Open LiquiDB
        2. Create X database instances
        3. Start all databases
        4. Notice slow performance
    validations:
      required: true

  - type: input
    id: expected-time
    attributes:
      label: Expected Time
      description: How long should this operation take? (e.g., "2 seconds", "instant")
      placeholder: 2 seconds
    validations:
      required: false

  - type: input
    id: actual-time
    attributes:
      label: Actual Time
      description: How long does it actually take? (e.g., "10 seconds", "30 seconds")
      placeholder: 10 seconds
    validations:
      required: true

  - type: input
    id: database-count
    attributes:
      label: Number of Databases
      description: How many database instances do you have configured?
      placeholder: 5
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: Your OS version
      placeholder: macOS 14.5
    validations:
      required: true

  - type: input
    id: liquidb-version
    attributes:
      label: LiquiDB Version
      description: The version of LiquiDB you're using
      placeholder: 1.6.0
    validations:
      required: true

  - type: textarea
    id: system-specs
    attributes:
      label: System Specifications
      description: Your system specifications (CPU, RAM, etc.)
      placeholder: |
        - CPU: Apple M1 Pro
        - RAM: 16GB
        - Storage: SSD
      render: shell

  - type: textarea
    id: logs
    attributes:
      label: Logs/Profiling Data
      description: Any relevant logs, profiling data, or performance metrics
      placeholder: Paste logs or metrics here...
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or screen recordings showing the performance issue
      placeholder: Drag and drop media here or paste URLs

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the performance issue
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true
        - label: I have included all relevant information above
          required: true
        - label: I have tested this on the latest version of LiquiDB
          required: false

