name: 🎨 UI/UX Issue
description: Report a user interface or user experience problem
title: "[UI/UX]: "
labels: ["ui/ux", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a UI/UX issue! Your feedback helps us improve the user experience.

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: A clear and concise description of the UI/UX issue
      placeholder: Describe the issue...
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of UI/UX issue is this?
      options:
        - Visual Bug
        - Layout Problem
        - Responsiveness Issue
        - Accessibility Issue
        - Usability Problem
        - Design Inconsistency
        - Missing Visual Feedback
        - Confusing Interface
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Where does this occur?
      description: Which part of the application is affected?
      placeholder: |
        - Main dashboard
        - Database settings dialog
        - Add database dialog
        - Sidebar
        - System stats panel
        - Other: ...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See issue
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen from a UI/UX perspective?
      placeholder: The interface should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: The interface...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Minor (cosmetic)
        - Moderate (affects usability)
        - Major (blocks functionality)
        - Critical (makes feature unusable)
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: Your OS version
      placeholder: macOS 14.5
    validations:
      required: true

  - type: input
    id: liquidb-version
    attributes:
      label: LiquiDB Version
      description: The version of LiquiDB you're using
      placeholder: 1.6.0
    validations:
      required: true

  - type: input
    id: screen-resolution
    attributes:
      label: Screen Resolution
      description: Your screen resolution (if relevant)
      placeholder: 2560x1440
    validations:
      required: false

  - type: dropdown
    id: theme
    attributes:
      label: Theme
      description: Which theme are you using?
      options:
        - Light
        - Dark
        - System
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Screenshots showing the issue (required for visual issues)
      placeholder: Drag and drop screenshots here or paste image URLs
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Suggested Solution
      description: If you have ideas for how to fix or improve this, describe them here
      placeholder: |
        - I think it should...
        - Maybe we could...
        - A better approach might be...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the UI/UX issue
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true
        - label: I have included all relevant information above
          required: true
        - label: I have tested this on the latest version of LiquiDB
          required: false

